In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sehaj1104/indian-road-accident-dataset-20222025/indian_roads_dataset.csv
/kaggle/input/datasets/talhasiddique123/events-and-holidays-2025-2035/Global_Holidays_2025_2035.csv
/kaggle/input/datasets/ameydilipmorye/indian-rainfall-and-weather-data/india_weather_rainfall_data.xlsx
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/README.md
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/geojson/new_delhi.json
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-24_to_2024-08-24_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-13_to_2024-08-13_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-20_to_2024-08-20_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-30_to_2024-08-30_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-25_to_2024-08-25_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-21_to_2024-08-21_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-12_to_2024-08-12_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-19_to_2024-08-19_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-28_to_2024-08-28_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-15_to_2024-08-15_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-14_to_2024-08-14_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-11_to_2024-08-11_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-17_to_2024-08-17_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-27_to_2024-08-27_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-26_to_2024-08-26_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-18_to_2024-08-18_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-23_to_2024-08-23_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-29_to_2024-08-29_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-22_to_2024-08-22_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson/new_delhi__2024-08-16_to_2024-08-16_.geojson
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/facility/features_geopkg.json
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/global_metrics/2024_city_rush_hour.json
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/global_metrics/new_delhi_2024_urban_traffic.json
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/global_metrics/2024_urban_rush_hour.json
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/global_metrics/new_delhi_2024_city_traffic.json
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/weekday_stats/2024_week_day_time_city.csv
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/weekday_stats/2024_week_day_speed_city.csv
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/weekday_stats/2024_week_day_congestion_urban.csv
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/weekday_stats/2024_week_day_congestion_city.csv
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/weekday_stats/2024_week_day_speed_urban.csv
/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/weekday_stats/2024_week_day_time_urban.csv

In [2]:
import os

base_path = "/kaggle/input"

for root, dirs, files in os.walk(base_path):
    level = root.replace(base_path, "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}  └── {file}")

input/
  datasets/
    sehaj1104/
      indian-road-accident-dataset-20222025/
        └── indian_roads_dataset.csv
    talhasiddique123/
      events-and-holidays-2025-2035/
        └── Global_Holidays_2025_2035.csv
    ameydilipmorye/
      indian-rainfall-and-weather-data/
        └── india_weather_rainfall_data.xlsx
    rawsi18/
      new-delhi-traffic-probe-and-analytics-2024/
        new_delhi_traffic_dataset/
          └── README.md
          geojson/
            └── new_delhi.json
          probe_counts/
            geojson/
              └── new_delhi__2024-08-24_to_2024-08-24_.geojson
              └── new_delhi__2024-08-13_to_2024-08-13_.geojson
              └── new_delhi__2024-08-20_to_2024-08-20_.geojson
              └── new_delhi__2024-08-30_to_2024-08-30_.geojson
              └── new_delhi__2024-08-25_to_2024-08-25_.geojson
              └── new_delhi__2024-08-21_to_2024-08-21_.geojson
              └── new_delhi__2024-08-12_to_2024-08-12_.geojson
              └── new_delhi__2024-08-19_to_2024-08-19_.geojson
              └── new_delhi__2024-08-28_to_2024-08-28_.geojson
              └── new_delhi__2024-08-15_to_2024-08-15_.geojson
              └── new_delhi__2024-08-14_to_2024-08-14_.geojson
              └── new_delhi__2024-08-11_to_2024-08-11_.geojson
              └── new_delhi__2024-08-17_to_2024-08-17_.geojson
              └── new_delhi__2024-08-27_to_2024-08-27_.geojson
              └── new_delhi__2024-08-26_to_2024-08-26_.geojson
              └── new_delhi__2024-08-18_to_2024-08-18_.geojson
              └── new_delhi__2024-08-23_to_2024-08-23_.geojson
              └── new_delhi__2024-08-29_to_2024-08-29_.geojson
              └── new_delhi__2024-08-22_to_2024-08-22_.geojson
              └── new_delhi__2024-08-16_to_2024-08-16_.geojson
          facility/
            └── features_geopkg.json
          global_metrics/
            └── 2024_city_rush_hour.json
            └── new_delhi_2024_urban_traffic.json
            └── 2024_urban_rush_hour.json
            └── new_delhi_2024_city_traffic.json
          weekday_stats/
            └── 2024_week_day_time_city.csv
            └── 2024_week_day_speed_city.csv
            └── 2024_week_day_congestion_urban.csv
            └── 2024_week_day_congestion_city.csv
            └── 2024_week_day_speed_urban.csv
            └── 2024_week_day_time_urban.csv

In [3]:
import os
import pandas as pd
import numpy as np

print("Kaggle environment ready")

BASE = "/kaggle/input"

print("\nAvailable datasets:")
for item in os.listdir(BASE):
    print(" -", item)

Kaggle environment ready

Available datasets:
 - datasets

In [4]:
import os

DATASETS_PATH = "/kaggle/input/datasets"

for root, dirs, files in os.walk(DATASETS_PATH):
    level = root.replace(DATASETS_PATH, "").count(os.sep)

    if level <= 4:
        print("\n" + root)

        for f in files[:10]:
            print("   └──", f)

/kaggle/input/datasets

/kaggle/input/datasets/sehaj1104

/kaggle/input/datasets/sehaj1104/indian-road-accident-dataset-20222025
   └── indian_roads_dataset.csv

/kaggle/input/datasets/talhasiddique123

/kaggle/input/datasets/talhasiddique123/events-and-holidays-2025-2035
   └── Global_Holidays_2025_2035.csv

/kaggle/input/datasets/ameydilipmorye

/kaggle/input/datasets/ameydilipmorye/indian-rainfall-and-weather-data
   └── india_weather_rainfall_data.xlsx

/kaggle/input/datasets/rawsi18

/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024

/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset
   └── README.md

/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/geojson
   └── new_delhi.json

/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts

/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/facility
   └── features_geopkg.json

/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/global_metrics
   └── 2024_city_rush_hour.json
   └── new_delhi_2024_urban_traffic.json
   └── 2024_urban_rush_hour.json
   └── new_delhi_2024_city_traffic.json

/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/weekday_stats
   └── 2024_week_day_time_city.csv
   └── 2024_week_day_speed_city.csv
   └── 2024_week_day_congestion_urban.csv
   └── 2024_week_day_congestion_city.csv
   └── 2024_week_day_speed_urban.csv
   └── 2024_week_day_time_urban.csv

In [5]:
# ==============================
# SMARTTRAFFICOPS DATASET PATHS
# ==============================

TRAFFIC_BASE = "/kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset"

TRAFFIC_PATH = os.path.join(
    TRAFFIC_BASE,
    "probe_counts",
    "geojson"
)

WEATHER_PATH = "/kaggle/input/datasets/ameydilipmorye/indian-rainfall-and-weather-data/india_weather_rainfall_data.xlsx"

ACCIDENT_PATH = "/kaggle/input/datasets/sehaj1104/indian-road-accident-dataset-20222025/indian_roads_dataset.csv"

HOLIDAY_PATH = "/kaggle/input/datasets/talhasiddique123/events-and-holidays-2025-2035/Global_Holidays_2025_2035.csv"

print("Traffic folder :", TRAFFIC_PATH)
print("Weather file   :", WEATHER_PATH)
print("Accident file  :", ACCIDENT_PATH)
print("Holiday file   :", HOLIDAY_PATH)

print("\nTraffic files:")
print(len(os.listdir(TRAFFIC_PATH)))

Traffic folder : /kaggle/input/datasets/rawsi18/new-delhi-traffic-probe-and-analytics-2024/new_delhi_traffic_dataset/probe_counts/geojson
Weather file   : /kaggle/input/datasets/ameydilipmorye/indian-rainfall-and-weather-data/india_weather_rainfall_data.xlsx
Accident file  : /kaggle/input/datasets/sehaj1104/indian-road-accident-dataset-20222025/indian_roads_dataset.csv
Holiday file   : /kaggle/input/datasets/talhasiddique123/events-and-holidays-2025-2035/Global_Holidays_2025_2035.csv

Traffic files:
20

In [6]:
import geopandas as gpd

first_file = sorted(os.listdir(TRAFFIC_PATH))[0]
first_path = os.path.join(TRAFFIC_PATH, first_file)

print("File:", first_file)

traffic = gpd.read_file(first_path)

print("\nShape:", traffic.shape)

print("\nColumns:")
print(traffic.columns.tolist())

print("\nData types:")
print(traffic.dtypes)

File: new_delhi__2024-08-11_to_2024-08-11_.geojson

Shape: (24939, 17)

Columns:
['jobName', 'creationTime', 'segmentId', 'newSegmentId', 'speedLimit', 'frc', 'streetName', 'distance', 'segmentProbeCounts', 'userPreference', 'dateRanges', 'timeSets', 'networkName', 'zoneId', 'probeSource', 'mapsVersions', 'geometry']

Data types:
jobName                            object
creationTime          datetime64[ms, UTC]
segmentId                         float64
newSegmentId                       object
speedLimit                        float64
frc                               float64
streetName                         object
distance                          float64
segmentProbeCounts                 object
userPreference                     object
dateRanges                         object
timeSets                           object
networkName                        object
zoneId                             object
probeSource                        object
mapsVersions                       object
geometry                         geometry
dtype: object

In [7]:
print("Missing values:")
print(traffic.isnull().sum())

Missing values:
jobName               24938
creationTime          24938
segmentId                 1
newSegmentId              1
speedLimit                1
frc                       1
streetName             2230
distance                  1
segmentProbeCounts        1
userPreference        24938
dateRanges            24938
timeSets              24938
networkName           24938
zoneId                24938
probeSource           24938
mapsVersions          24938
geometry                  1
dtype: int64

In [8]:
traffic = traffic[
    traffic["segmentProbeCounts"].notna()
].copy()

print("Shape after removing empty record:", traffic.shape)

print("\nMissing values in important columns:")
print(
    traffic[
        [
            "segmentId",
            "newSegmentId",
            "speedLimit",
            "frc",
            "streetName",
            "distance",
            "segmentProbeCounts"
        ]
    ].isnull().sum()
)

Shape after removing empty record: (24938, 17)

Missing values in important columns:
segmentId                0
newSegmentId             0
speedLimit               0
frc                      0
streetName            2229
distance                 0
segmentProbeCounts       0
dtype: int64

In [9]:
missing_street = traffic[traffic["streetName"].isna()].copy()

print("Rows with missing streetName:", len(missing_street))

print("\nProbe count records available:")
print(missing_street["segmentProbeCounts"].apply(len).value_counts().sort_index())

print("\nFirst 5 missing-street records:")
print(
    missing_street[
        ["segmentId", "newSegmentId", "speedLimit", "frc",
         "distance", "segmentProbeCounts"]
    ].head()
)

Rows with missing streetName: 2229

Probe count records available:
segmentProbeCounts
24    2229
Name: count, dtype: int64

First 5 missing-street records:
       segmentId                           newSegmentId  speedLimit  frc  \
7  -1.356013e+13  -00004e30-3400-0400-0000-0000008bb108        45.0  6.0
20 -1.356018e+13  -00004e30-3400-0400-0000-0000008bb6b1        45.0  6.0
42 -1.356013e+13  -00004e30-3400-0400-0000-0000008bc058        45.0  6.0
45 -1.356013e+13  -00004e30-3400-0400-0000-0000008bc1eb        45.0  6.0
70 -1.356018e+13  -00004e30-3400-0400-0000-0000008bd1bc        45.0  6.0

    distance                                 segmentProbeCounts
7     477.66  [{'timeSet': 2, 'dateRange': 1, 'probeCount': ...
20      8.91  [{'timeSet': 2, 'dateRange': 1, 'probeCount': ...
42     30.37  [{'timeSet': 2, 'dateRange': 1, 'probeCount': ...
45     31.15  [{'timeSet': 2, 'dateRange': 1, 'probeCount': ...
70     38.92  [{'timeSet': 2, 'dateRange': 1, 'probeCount': ...

In [10]:
print("Missing streetName rows:", len(missing_street))

print("Unique segmentId:",
      missing_street["segmentId"].nunique())

print("Unique newSegmentId:",
      missing_street["newSegmentId"].nunique())

print("\nMissing streetName percentage:",
      round(len(missing_street) / len(traffic) * 100, 2), "%")

Missing streetName rows: 2229
Unique segmentId: 2229
Unique newSegmentId: 2229

Missing streetName percentage: 8.94 %

In [11]:
import pandas as pd

# Keep only columns required for traffic modeling
traffic_hourly = traffic[
    [
        "segmentId",
        "newSegmentId",
        "speedLimit",
        "frc",
        "streetName",
        "distance",
        "segmentProbeCounts"
    ]
].copy()

# Expand the 24 hourly records
traffic_hourly["hourly_data"] = traffic_hourly["segmentProbeCounts"]

traffic_hourly = traffic_hourly.explode("hourly_data", ignore_index=True)

# Extract values from each dictionary
traffic_hourly["timeSet"] = traffic_hourly["hourly_data"].apply(
    lambda x: x["timeSet"]
)

traffic_hourly["dateRange"] = traffic_hourly["hourly_data"].apply(
    lambda x: x["dateRange"]
)

traffic_hourly["probeCount"] = traffic_hourly["hourly_data"].apply(
    lambda x: x["probeCount"]
)

# Remove nested columns
traffic_hourly = traffic_hourly.drop(
    columns=["segmentProbeCounts", "hourly_data"]
)

print("Shape:", traffic_hourly.shape)

print("\nColumns:")
print(traffic_hourly.columns.tolist())

print("\nFirst 10 rows:")
print(traffic_hourly.head(10))

Shape: (598512, 9)

Columns:
['segmentId', 'newSegmentId', 'speedLimit', 'frc', 'streetName', 'distance', 'timeSet', 'dateRange', 'probeCount']

First 10 rows:
      segmentId                           newSegmentId  speedLimit  frc  \
0 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
1 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
2 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
3 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
4 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
5 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
6 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
7 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
8 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0
9 -1.356011e+13  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0

          streetName  distance  timeSet  dateRange  probeCount
0  Ghata Masjid Road     20.87        2          1           4
1  Ghata Masjid Road     20.87        3          1           2
2  Ghata Masjid Road     20.87        4          1           1
3  Ghata Masjid Road     20.87        5          1           0
4  Ghata Masjid Road     20.87        6          1           0
5  Ghata Masjid Road     20.87        7          1           0
6  Ghata Masjid Road     20.87        8          1           0
7  Ghata Masjid Road     20.87        9          1           2
8  Ghata Masjid Road     20.87       10          1           2
9  Ghata Masjid Road     20.87       11          1           4

In [12]:
# Date for the current traffic file
traffic_date = pd.to_datetime("2024-08-11")

# Convert timeSet to actual hour
traffic_hourly["hour"] = traffic_hourly["timeSet"] - 2

# Create date column
traffic_hourly["date"] = traffic_date

# Create timestamp
traffic_hourly["timestamp"] = (
    traffic_hourly["date"]
    + pd.to_timedelta(traffic_hourly["hour"], unit="h")
)

# Reorder columns
traffic_hourly = traffic_hourly[
    [
        "timestamp",
        "date",
        "hour",
        "segmentId",
        "newSegmentId",
        "speedLimit",
        "frc",
        "streetName",
        "distance",
        "probeCount"
    ]
]

print("Shape:", traffic_hourly.shape)

print("\nFirst 10 rows:")
print(traffic_hourly.head(10))

print("\nLast 5 rows:")
print(traffic_hourly.tail())

Shape: (598512, 10)

First 10 rows:
            timestamp       date  hour     segmentId  \
0 2024-08-11 00:00:00 2024-08-11     0 -1.356011e+13
1 2024-08-11 01:00:00 2024-08-11     1 -1.356011e+13
2 2024-08-11 02:00:00 2024-08-11     2 -1.356011e+13
3 2024-08-11 03:00:00 2024-08-11     3 -1.356011e+13
4 2024-08-11 04:00:00 2024-08-11     4 -1.356011e+13
5 2024-08-11 05:00:00 2024-08-11     5 -1.356011e+13
6 2024-08-11 06:00:00 2024-08-11     6 -1.356011e+13
7 2024-08-11 07:00:00 2024-08-11     7 -1.356011e+13
8 2024-08-11 08:00:00 2024-08-11     8 -1.356011e+13
9 2024-08-11 09:00:00 2024-08-11     9 -1.356011e+13

                            newSegmentId  speedLimit  frc         streetName  \
0  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
1  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
2  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
3  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
4  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
5  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
6  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
7  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
8  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road
9  -00004e30-3400-0400-0000-0000008bad86        45.0  6.0  Ghata Masjid Road

   distance  probeCount
0     20.87           4
1     20.87           2
2     20.87           1
3     20.87           0
4     20.87           0
5     20.87           0
6     20.87           0
7     20.87           2
8     20.87           2
9     20.87           4

Last 5 rows:
                 timestamp       date  hour     segmentId  \
598507 2024-08-11 19:00:00 2024-08-11    19  1.356034e+13
598508 2024-08-11 20:00:00 2024-08-11    20  1.356034e+13
598509 2024-08-11 21:00:00 2024-08-11    21  1.356034e+13
598510 2024-08-11 22:00:00 2024-08-11    22  1.356034e+13
598511 2024-08-11 23:00:00 2024-08-11    23  1.356034e+13

                                newSegmentId  speedLimit  frc streetName  \
598507  fffbe947-5a15-42df-b2c8-6e242db662d4        45.0  6.0       None
598508  fffbe947-5a15-42df-b2c8-6e242db662d4        45.0  6.0       None
598509  fffbe947-5a15-42df-b2c8-6e242db662d4        45.0  6.0       None
598510  fffbe947-5a15-42df-b2c8-6e242db662d4        45.0  6.0       None
598511  fffbe947-5a15-42df-b2c8-6e242db662d4        45.0  6.0       None

        distance  probeCount
598507      35.1          11
598508      35.1           9
598509      35.1           7
598510      35.1           5
598511      35.1           3

In [13]:
# ==============================
# TRAFFIC DATA VALIDATION
# ==============================

print("Missing values:")
print(traffic_hourly.isnull().sum())

print("\nNegative probe counts:",
      (traffic_hourly["probeCount"] < 0).sum())

print("Negative speed limits:",
      (traffic_hourly["speedLimit"] < 0).sum())

print("Negative distances:",
      (traffic_hourly["distance"] < 0).sum())

print("\nDuplicate segment + timestamp rows:",
      traffic_hourly.duplicated(
          subset=["newSegmentId", "timestamp"]
      ).sum())

print("\nProbe count summary:")
print(traffic_hourly["probeCount"].describe())

print("\nUnique segments:",
      traffic_hourly["newSegmentId"].nunique())

print("Unique timestamps:",
      traffic_hourly["timestamp"].nunique())

Missing values:
timestamp           0
date                0
hour                0
segmentId           0
newSegmentId        0
speedLimit          0
frc                 0
streetName      53496
distance            0
probeCount          0
dtype: int64

Negative probe counts: 0
Negative speed limits: 0
Negative distances: 0

Duplicate segment + timestamp rows: 0

Probe count summary:
count    598512.000000
mean         96.379499
std         157.612645
min           0.000000
25%           7.000000
50%          34.000000
75%         113.000000
max        2207.000000
Name: probeCount, dtype: float64

Unique segments: 24938
Unique timestamps: 24

In [14]:
import os
import re
import pandas as pd
import geopandas as gpd

traffic_files = sorted([
    f for f in os.listdir(TRAFFIC_PATH)
    if f.endswith(".geojson")
])

all_traffic = []

print("Total traffic files:", len(traffic_files))

for i, filename in enumerate(traffic_files, 1):

    print(f"\nProcessing {i}/{len(traffic_files)}: {filename}")

    filepath = os.path.join(TRAFFIC_PATH, filename)

    # Read GeoJSON
    temp = gpd.read_file(filepath)

    # Remove empty probe-count records
    temp = temp[temp["segmentProbeCounts"].notna()].copy()

    # Keep only required columns
    temp = temp[
        [
            "segmentId",
            "newSegmentId",
            "speedLimit",
            "frc",
            "streetName",
            "distance",
            "segmentProbeCounts"
        ]
    ]

    # Expand 24 hourly records
    temp = temp.explode(
        "segmentProbeCounts",
        ignore_index=True
    )

    # Extract values
    temp["timeSet"] = temp["segmentProbeCounts"].apply(
        lambda x: x["timeSet"]
    )

    temp["dateRange"] = temp["segmentProbeCounts"].apply(
        lambda x: x["dateRange"]
    )

    temp["probeCount"] = temp["segmentProbeCounts"].apply(
        lambda x: x["probeCount"]
    )

    # Remove nested column
    temp = temp.drop(
        columns=["segmentProbeCounts"]
    )

    # Extract date from filename
    date_match = re.search(
        r"(\d{4}-\d{2}-\d{2})",
        filename
    )

    if date_match:
        traffic_date = pd.to_datetime(
            date_match.group(1)
        )
    else:
        print("WARNING: Date not found:", filename)
        continue

    # Convert timeSet → hour
    temp["hour"] = temp["timeSet"] - 2

    # Add date
    temp["date"] = traffic_date

    # Create timestamp
    temp["timestamp"] = (
        temp["date"]
        + pd.to_timedelta(
            temp["hour"],
            unit="h"
        )
    )

    # Keep final columns
    temp = temp[
        [
            "timestamp",
            "date",
            "hour",
            "segmentId",
            "newSegmentId",
            "speedLimit",
            "frc",
            "streetName",
            "distance",
            "probeCount"
        ]
    ]

    print("Rows:", len(temp))

    all_traffic.append(temp)

# Combine all 20 days
traffic_all = pd.concat(
    all_traffic,
    ignore_index=True
)

print("\n==============================")
print("FINAL TRAFFIC DATASET")
print("==============================")

print("Shape:", traffic_all.shape)

print("\nDate range:")
print(traffic_all["date"].min(), "→", traffic_all["date"].max())

print("\nUnique dates:",
      traffic_all["date"].nunique())

print("Unique segments:",
      traffic_all["newSegmentId"].nunique())

print("Unique timestamps:",
      traffic_all["timestamp"].nunique())

Total traffic files: 20

Processing 1/20: new_delhi__2024-08-11_to_2024-08-11_.geojson
Rows: 598512

Processing 2/20: new_delhi__2024-08-12_to_2024-08-12_.geojson
Rows: 598512

Processing 3/20: new_delhi__2024-08-13_to_2024-08-13_.geojson
Rows: 598512

Processing 4/20: new_delhi__2024-08-14_to_2024-08-14_.geojson
Rows: 598512

Processing 5/20: new_delhi__2024-08-15_to_2024-08-15_.geojson
Rows: 598512

Processing 6/20: new_delhi__2024-08-16_to_2024-08-16_.geojson
Rows: 598512

Processing 7/20: new_delhi__2024-08-17_to_2024-08-17_.geojson
Rows: 598512

Processing 8/20: new_delhi__2024-08-18_to_2024-08-18_.geojson
Rows: 598512

Processing 9/20: new_delhi__2024-08-19_to_2024-08-19_.geojson
Rows: 598512

Processing 10/20: new_delhi__2024-08-20_to_2024-08-20_.geojson
Rows: 598512

Processing 11/20: new_delhi__2024-08-21_to_2024-08-21_.geojson
Rows: 598512

Processing 12/20: new_delhi__2024-08-22_to_2024-08-22_.geojson
Rows: 598512

Processing 13/20: new_delhi__2024-08-23_to_2024-08-23_.geojson
Rows: 598512

Processing 14/20: new_delhi__2024-08-24_to_2024-08-24_.geojson
Rows: 598512

Processing 15/20: new_delhi__2024-08-25_to_2024-08-25_.geojson
Rows: 598512

Processing 16/20: new_delhi__2024-08-26_to_2024-08-26_.geojson
Rows: 598512

Processing 17/20: new_delhi__2024-08-27_to_2024-08-27_.geojson
Rows: 598512

Processing 18/20: new_delhi__2024-08-28_to_2024-08-28_.geojson
Rows: 598512

Processing 19/20: new_delhi__2024-08-29_to_2024-08-29_.geojson
Rows: 598512

Processing 20/20: new_delhi__2024-08-30_to_2024-08-30_.geojson
Rows: 598512

==============================
FINAL TRAFFIC DATASET
==============================
Shape: (11970240, 10)

Date range:
2024-08-11 00:00:00 → 2024-08-30 00:00:00

Unique dates: 20
Unique segments: 24938
Unique timestamps: 480

In [15]:
import pandas as pd
import os

WEATHER_PATH = "/kaggle/input/datasets/ameydilipmorye/indian-rainfall-and-weather-data/india_weather_rainfall_data.xlsx"

print("Weather file exists:", os.path.exists(WEATHER_PATH))

df = pd.read_excel(WEATHER_PATH)

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 rows:")
display(df.head())

Weather file exists: True
Shape: (970339, 15)

Columns:
['date_of_record', 'month', 'season', 'station_name', 'state', 'district', 'avg_temp', 'min_temp', 'max_temp', 'wind_speed', 'air_pressure', 'elevation', 'latitude', 'longitude', 'rainfall']

Data types:
date_of_record    datetime64[ns]
month                     object
season                    object
station_name              object
state                     object
district                  object
avg_temp                 float64
min_temp                 float64
max_temp                 float64
wind_speed               float64
air_pressure             float64
elevation                  int64
latitude                 float64
longitude                float64
rainfall                 float64
dtype: object

First 5 rows:

,date_of_record,month,season,station_name,state,district,avg_temp,min_temp,max_temp,wind_speed,air_pressure,elevation,latitude,longitude,rainfall
0,2021-01-02,January,Winter,Gulmarg,JK,Baramulla,-2.2,-6.6,-0.8,2.2,1020.0,2652,34.05,74.4,0.1
1,2021-01-03,January,Winter,Gulmarg,JK,Baramulla,-3.6,-4.6,-1.8,3.7,1019.5,2652,34.05,74.4,4.4
2,2021-01-04,January,Winter,Gulmarg,JK,Baramulla,-3.0,-4.5,-1.1,2.1,1022.0,2652,34.05,74.4,2.3
3,2021-01-05,January,Winter,Gulmarg,JK,Baramulla,-3.3,-5.1,-1.2,2.8,1015.6,2652,34.05,74.4,35.0
4,2021-01-06,January,Winter,Gulmarg,JK,Baramulla,-3.9,-8.3,-1.0,3.4,1015.3,2652,34.05,74.4,25.5

In [16]:
# Weather dataset - missing value analysis

missing_count = df.isnull().sum()
missing_percentage = (missing_count / len(df)) * 100

weather_missing = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage.round(2)
})

print("Missing values in weather dataset:")
display(weather_missing)

print("\nTotal rows:", len(df))
print("Total columns:", len(df.columns))

Missing values in weather dataset:

                Missing_Count  Missing_Percentage
date_of_record              0                0.00
month                       0                0.00
season                      0                0.00
station_name                0                0.00
state                       0                0.00
district                    0                0.00
avg_temp                    0                0.00
min_temp                43898                4.52
max_temp               110598               11.40
wind_speed             274444               28.28
air_pressure           304664               31.40
elevation                   0                0.00
latitude                    0                0.00
longitude                   0                0.00
rainfall               257554               26.54

Total rows: 970339
Total columns: 15

In [17]:
# ============================================
# SAVE DATASET 1 - TRAFFIC DATASET
# ============================================

TRAFFIC_OUTPUT = "/kaggle/working/traffic_dataset_2024.csv"

traffic_all.to_csv(TRAFFIC_OUTPUT, index=False)

print("Traffic dataset saved successfully!")
print("Path:", TRAFFIC_OUTPUT)
print("Shape:", traffic_all.shape)
print("File size (MB):", round(os.path.getsize(TRAFFIC_OUTPUT) / (1024**2), 2))

Traffic dataset saved successfully!
Path: /kaggle/working/traffic_dataset_2024.csv
Shape: (11970240, 10)
File size (MB): 1403.44

In [18]:
# ============================================
# WEATHER DATASET - MISSING VALUES BY STATION
# ============================================

weather_cols = [
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "rainfall"
]

station_missing = df.groupby("station_name")[weather_cols].apply(
    lambda x: x.isna().sum()
)

print("Missing values by station:")
display(station_missing.head(20))

print("\nTotal stations:", df["station_name"].nunique())

print("\nStations with the highest total missing values:")
station_missing["total_missing"] = station_missing.sum(axis=1)

display(
    station_missing
    .sort_values("total_missing", ascending=False)
    .head(20)
)

Missing values by station:

                       min_temp  max_temp  wind_speed  air_pressure  rainfall
station_name
Agartala                    865      1809        2203          2203      1169
Agatti / Kavaratti            0         0           0             0         0
Agra                          0         0           0             0      2834
Agumbe                        0         0           0             0         0
Ahmadabad                   118       247         350           561      1956
Ahmadnagar                    0         0           0             0         0
Aijal                         0         0           0             0         0
Ajmer                       194       111        1843          1843      1502
Akola                       484      3664        4298          4298      3256
Alapuzha                      0         0           0             0         0
Alibag                        0         0           0             0       908
Aligarh                       0         0           0             0         0
Allahabad / Bamhrauli         0         0           0             0      1417
Alwar                         0         0           0             0         0
Ambala                      179       360        2199          2199      1474
Ambala / Amb?la               0         0           0             0         0
Ambikapur                   104       471        1860          1860      1228
Amini Divi                  188       430        2203          2203      1354
Amraoti                      11       331         799           799       544
Amreli                        0         0           0             0         0

Total stations: 406

Stations with the highest total missing values:

,min_temp,max_temp,wind_speed,air_pressure,rainfall,total_missing
station_name,,,,,,
Akola,484,3664,4298,4298,3256,16000
Srinagar,326,1922,2664,2664,2566,10142
Aurangabad Chikalthan Aerodrome,1428,1828,2197,2198,2116,9767
Aurangabad,1428,1828,2197,2198,2116,9767
Jabalpur,1420,1719,2131,2131,1989,9390
Bhuj-Rudramata,232,1805,2202,2202,1956,8397
Bhopal / Bairagarh,603,1804,2170,2183,1622,8382
Pbo Raipur,1675,1676,1676,1676,1674,8377
Mana / Raipur,1675,1676,1676,1676,1674,8377
Raipur / Phundardih,1675,1676,1676,1676,1674,8377
Rajkot,170,1794,2197,2198,1908,8267
Agartala,865,1809,2203,2203,1169,8249
Veraval,221,1798,2188,2188,1788,8183
Guna,236,1799,2198,2198,1668,8099
Satna,338,1771,2193,2193,1591,8086
Sholapur,173,1776,2200,2200,1730,8079
Indore,291,1757,2141,2154,1684,8027
Surat,261,1774,2163,2162,1655,8015
Surat / Magdala,261,1774,2163,2162,1655,8015
Ratnagiri,330,1853,2203,2203,1395,7984

In [19]:
# ============================================
# WEATHER DATASET - DELHI PERIOD CHECK
# ============================================

# Convert date just to be safe
df["date_of_record"] = pd.to_datetime(df["date_of_record"])

# Check Delhi-related records
delhi_weather = df[
    (df["date_of_record"] >= "2024-08-11") &
    (df["date_of_record"] <= "2024-08-30")
].copy()

print("Delhi-period weather rows:", len(delhi_weather))

print("\nDate range:")
print(delhi_weather["date_of_record"].min(), "→", delhi_weather["date_of_record"].max())

print("\nStations in this period:")
print(delhi_weather["station_name"].unique())

print("\nStates in this period:")
print(delhi_weather["state"].unique())

print("\nDistricts in this period:")
print(delhi_weather["district"].unique())

print("\nMissing values in Delhi-period weather data:")
display(delhi_weather.isnull().sum())

print("\nShape:")
print(delhi_weather.shape)

Delhi-period weather rows: 7430

Date range:
2024-08-11 00:00:00 → 2024-08-30 00:00:00

Stations in this period:
['Gulmarg' 'Srinagar' 'Qazi Gund' 'Banihal' 'Jammu'
 'Pathankot / Path?nkot' 'Dharmsala' 'Manali' 'Amritsar' 'Una' 'Mandi'
 'Sundernagar / Sundarnagar' 'Bilaspur' 'Bhuntar' 'Shimla' 'Bhatinda'
 'Ludhiana' 'Patiala' 'Ambala' 'Ambala / Amb?la' 'Chandigarh / S?rajpur'
 'Dharmpur' 'Dehradun' 'Tehri' 'Ganganagar' 'Hissar' 'Karnal' 'Meerut'
 'Najibabad' 'Nainital' 'Mukteshwar Kumaon' 'Pantnagar' 'Bikaner' 'Churu'
 'Pilani' 'Rohtak' 'Narnaul' 'New Delhi / Palam' 'New Delhi / Safdarjung'
 'Moradabad' 'Rampur' 'Bareilly' 'Pasighat' 'Phalodi' 'Sikar' 'Alwar'
 'Agra' 'Aligarh' 'Shahjahanpur' 'Hardoi' 'Bahraich' 'Nautanwa'
 'Kalimpong' 'Gangtok' 'North Lakhimpur' 'Dibrugarh / Mohanbari'
 'Jaisalmer' 'Jodhpur' 'Ajmer' 'Jaipur / Sanganer' 'Gwalior' 'Kanpur'
 'Kanpur / Chakeri' 'Lucknow' 'Lucknow / Amausi' 'Fursatganj / R?e Bareli'
 'Gorakhpur' 'Raxaul' 'Muzaffarpur' 'Darbhanga' 'Supaul' 'Forbesganj'
 'Siliguri' 'Jalpaiguri' 'Cooch Behar' 'Dhubri' 'Dhubri Rupsi' 'Goalpara'
 'Rangia' 'Gauhati' 'Majbat' 'Chaparmukh' 'Tezpur' 'Golaghat'
 'Jorhat / Lengrabhita' 'Barmer' 'Erinpura / Jawai Dam Site' 'Bhilwara'
 'Bundi' 'Kota Aerodrome' 'Sawai Madhopur' 'Sheopur' 'Shivpuri' 'Datia'
 'Jhansi' 'Nowgong' 'Orai' 'Hamirpur' 'Banda' 'Allahabad / Bamhrauli'
 'Varanasi / Babatpur' 'Ghazipur' 'Varanasi' 'Chapra' 'Patna' 'Bhagalpur'
 'Sabaur' 'Purnea' 'Malda' 'Balurghat' 'Barapani / Bara Pani'
 'Cherrapunji' 'Shillong' 'Haflong' 'Lumding' 'Kohima' 'Deesa' 'Mount Abu'
 'Udaipur Dabok' 'Udaipur' 'Chittorgarh' 'Rajgarh' 'Guna' 'Tikamgarh'
 'Khajuraho' 'Satna' 'Rewa' 'Sidhi' 'Daltonganj' 'Dehri' 'Gaya'
 'Berhampore' 'Kailashahar' 'Silchar' 'Imphal Tulihal' 'Naliya'
 'Bhuj-Rudramata' 'Kandla Aerodrome' 'New Kandla' 'Ahmadabad'
 'Gandhinagar' 'Ratlam' 'Ujjain' 'Shajapur' 'Bhopal / Bairagarh' 'Vidisha'
 'Sagar' 'Raisen' 'Damoh' 'Jabalpur' 'Umaria' 'Ambikapur'
 'Ranchi / Silwai' 'M. O. Ranchi' 'Panagarh / P?n?garh' 'Purulia'
 'Bankura' 'Shanti Niketan' 'Burdwan' 'Krishnanagar' 'Bagati'
 'Malanjkhand' 'Agartala' 'Aijal' 'Okha' 'Dwarka' 'Jamnagar' 'Rajkot'
 'Surendranagar' 'Vallabh Vidyanagar' 'Baroda / Vadodara'
 'Baroda Aerodrome' 'Dhar' 'Indore' 'Hoshangabad' 'Pachmarhi' 'Chhindwara'
 'Narsinghpur' 'Seoni' 'Mandla' 'Pendra Road' 'Sundargarh' 'Rourkela'
 'Jamshedpur' 'Midnapore' 'Uluberia' 'Calcutta / Alipore'
 'Calcutta / Dum Dum' 'Diamond Harbour' 'Canning' 'Porbandar' 'Keshod'
 'Amreli' 'Mahuva' 'Bhaunagar' 'Surat' 'Khargone' 'Jalgaon' 'Khandwa'
 'Betul' 'Nagpur Mayo Hospital' 'Nagpur Sonegaon' 'Gondia' 'Mana / Raipur'
 'Pbo Raipur' 'Raipur / Phundardih' 'Durg' 'Sambalpur' 'Jharsuguda'
 'Keongjhargarh' 'Baripada' 'Balasore' 'Contai' 'Digha' 'Veraval' 'Diu'
 'Bulsar' 'Daman' 'Nasik Ozar' 'Nasik' 'Malegaon' 'Buldana' 'Akola'
 'Washim / W?sh?m' 'Amraoti' 'Wardha' 'Yeotmal' 'Bramhapuri'
 'Rajnandgaon / R?j N?ndgaon' 'Angul' 'Cuttack' 'Bhubaneswar' 'Chandbali'
 'Paradip C. W. R.' 'Dahanu' 'Bombay / Juhu' 'Bombay / Santacruz'
 'T.B.I.A' 'Ahmadnagar' 'Jalna / Badnapur' 'Aurangabad'
 'Aurangabad Chikalthan Aerodrome' 'Parbhani' 'Nanded' 'Chandrapur'
 'Jagdalpur' 'Bhawanipatna' 'Gopalpur' 'Puri' 'Bombay / Colaba' 'Alibag'
 'Matheran' 'Poona' 'Poona / Lohogaon Aerodrome' 'Baramati' 'Jeur' 'Udgir'
 'Nizamabad' 'Medak' 'Ramgundam' 'Hanamkonda' 'Koraput' 'Kalingapatam'
 'Harnai' 'Ratnagiri' 'Mahabaleshwar' 'Satara' 'Sholapur' 'Gulbarga'
 'Bidar Airport' 'Hyderabad Airport' 'Nalgonda' 'Kothagudem' 'Khammam'
 'Tuni' 'Vishakhapatnam' 'Cwc Vishakhapatnam / Waltair' 'Kolhapur'
 'Sangli' 'Bagalkote / Mangoli' 'Bijapur' 'Mahabubnagar' 'Raichur'
 'Rentachintala' 'Vijayawada / Gannavaram' 'Nandigama' 'Machilipatnam'
 'Narsapur' 'Kakinada' 'Goa / Panjim' 'Vengurla' 'Goa / Dabolim Airport'
 'Mormugao' 'Belgaum' 'Belgaum / Sambra' 'Dharwad' 'Gadag' 'Bellary'
 'Parangipettai' 'Nandyal' 'Kurnool' 'Bapatla' 'Ongole' 'Karwar' 'Honavar'
 'Haveri / H?veri' 'Koppal' 'Shirali' 'Davangere / SM Krishna Ext.'
 'Chitradurga' 'Anantapur' 'Cuddapah' 'Kavali' 'Nellore' 'Agumbe'
 'Shimoga' 'Chickmagalur' 'Hassan' 'M.O. Agathi Airport / Kavaratti'
 'Arogyavaram' 'Chintamani / Sugut?ru' 'Tirupathi' 'Tiruttani' 'Madras'
 'Madras / Minambakkam' 'Mangalore / Bajpe' 'Mangalore / Panambur'
 'Madikeri' 'Mandya' 'Mysore' 'Bangalore' 'Bangalore / Hindustan Airport'
 'Dharmapuri' 'Tiruppattur' 'Vellore' 'Maya Bandar' 'Long Island'
 'Amini Divi' 'Kozhikode' 'Cannur' 'Nilambur' 'Udhagamandalam' 'Coonoor'
 'Coimbatore' 'M.O. Karipur Airport / Kondotti' 'Coimbatore / Peelamedu'
 'Chamarajnagar / Chamrajnagar' 'Salem' 'Cuddalore' 'Thanjavur'
 'M.O. Pondicherry / Puducherry' 'Port Blair' 'Palakkad'
 'Cochin Int. Airport / K?ladi' 'Kodaikanal' 'Yercaud' 'Valparai'
 'K. Paramathy' 'Tiruchchirapalli' 'Karaikal' 'Nagappattinam'
 'Atiramapattinam' 'Fort Cochin' 'Alapuzha' 'Cochin / Willingdon'
 'Punalur' 'Kottayam' 'Periakulum / Ellakkal' 'Thrissur'
 'Kovilangulam / Aruppukkottai' 'Madurai' 'Tondi' 'Pamban' 'Hut Bay'
 'Car Nicobar' 'Minicoy' 'Thiruvananthapuram' 'Palayankottai'
 'Kanniyakumari' 'Tuticorin New Port' 'Nancowry' 'Daman / Dam?n'
 'Surat / Magdala' 'Udaipur / Naramagra' 'Lengpui / Hmunpui'
 'Manipur Road / R?jb?ri' 'Vishakhapatnam / Gajuwaka'
 'Dehradun / R?ni Pokhri' 'Kangra / Chari' 'Jammu / R?mb?gh'
 'Ludhiana / Dor?ha' 'Shimla / Kanda' 'Agatti / Kavaratti'
 'Bangalore / Bengaluru / Devenahalli / BIAL 2 Wheeler Parking'
 'Cochin / K?ladi' 'Calicut / Kondotti' 'Hyderabad / Anthredigudam'
 'Jindal Vijaynagar' 'Ondal / And?l' 'Port Blair / Portblair / Austin?b?d'
 'Pondicherry / Auroville' 'Rajahmundry / R?j?nagaram'
 'Tirupati / Renigunta' 'Vizagapatam / Gajuwaka']

States in this period:
['JK' 'PB' 'HP' 'HR' 'CH' 'UP' 'RJ' 'DL' 'AR' 'WB' 'SK' 'AS' 'MP' 'BR'
 'ML' 'NL' 'GJ' 'TR' 'MN' 'MZ' 'OR' 'MH' 'CT' 'DD' 'KA' 'AP' 'GA' 'TN'
 'LD' 'AN' 'KL' 'PY']

Districts in this period:
['Baramulla' 'Srinagar' 'Anantnag' 'Ramban' 'Jammu' 'Pathankot' 'Kangra'
 'Kullu' 'Amritsar' 'Una' 'Mandi' 'Bilaspur' 'Shimla' 'Bathinda'
 'Ludhiana' 'Patiala' 'Ambala' 'Chandigarh' 'Solan' 'Dehradun'
 'Tehri Garhwal' 'Ganganagar' 'Hisar' 'Karnal' 'Meerut' 'Bijnor'
 'Nainital' 'Udham Singh Nagar' 'Bikaner' 'Churu' 'Jhunjhunu' 'Rohtak'
 'Mahendragarh' 'New Delhi' 'Moradabad' 'Rampur' 'Bareilly' 'East Siang'
 'Jodhpur' 'Sikar' 'Alwar' 'Agra' 'Aligarh' 'Shahjahanpur' 'Hardoi'
 'Bahraich' 'Maharajganj' 'Kalimpong' 'Gangtok' 'Lakhimpur' 'Dibrugarh'
 'Jaisalmer' 'Ajmer' 'Jaipur' 'Gwalior' 'Kanpur Nagar' 'Lucknow'
 'Rae Bareli' 'Gorakhpur' 'East Champaran' 'Muzaffarpur' 'Darbhanga'
 'Supaul' 'Araria' 'Jalpaiguri' 'Cooch Behar' 'Dhubri' 'Goalpara' 'Kamrup'
 'Kamrup Metropolitan' 'Udalguri' 'Nagaon' 'Sonitpur' 'Golaghat' 'Jorhat'
 'Barmer' 'Pali' 'Bhilwara' 'Bundi' 'Kota' 'Sawai Madhopur' 'Sheopur'
 'Shivpuri' 'Datia' 'Jhansi' 'Chhatarpur' 'Jalaun' 'Hamirpur' 'Banda'
 'Prayagraj' 'Varanasi' 'Ghazipur' 'Saran' 'Patna' 'Bhagalpur' 'Purnia'
 'Malda' 'Dakshin Dinajpur' 'Ri-Bhoi' 'East Khasi Hills' 'Dima Hasao'
 'Hojai' 'Kohima' 'Banaskantha' 'Sirohi' 'Udaipur' 'Chittorgarh' 'Rajgarh'
 'Guna' 'Tikamgarh' 'Satna' 'Rewa' 'Sidhi' 'Palamu' 'Rohtas' 'Gaya'
 'Murshidabad' 'Unakoti' 'Cachar' 'Imphal West' 'Kachchh' 'Ahmedabad'
 'Gandhinagar' 'Ratlam' 'Ujjain' 'Shajapur' 'Bhopal' 'Vidisha' 'Sagar'
 'Raisen' 'Damoh' 'Jabalpur' 'Umaria' 'Surguja' 'Ranchi'
 'Paschim Bardhaman' 'Purulia' 'Bankura' 'Birbhum' 'Purba Bardhaman'
 'Nadia' 'Hooghly' 'Balaghat' 'West Tripura' 'Aizawl' 'Devbhumi Dwarka'
 'Jamnagar' 'Rajkot' 'Surendranagar' 'Anand' 'Vadodara' 'Dhar' 'Indore'
 'Narmadapuram' 'Chhindwara' 'Narsinghpur' 'Seoni' 'Mandla'
 'Gaurela-Pendra-Marwahi' 'Sundargarh' 'East Singhbhum'
 'Paschim Medinipur' 'Howrah' 'Kolkata' 'South 24 Parganas' 'Porbandar'
 'Gir Somnath' 'Amreli' 'Bhavnagar' 'Surat' 'Khargone' 'Jalgaon' 'Khandwa'
 'Betul' 'Nagpur' 'Gondia' 'Raipur' 'Durg' 'Sambalpur' 'Jharsuguda'
 'Keonjhar' 'Mayurbhanj' 'Balasore' 'Purba Medinipur' 'Diu' 'Valsad'
 'Daman' 'Nashik' 'Buldhana' 'Akola' 'Washim' 'Amravati' 'Wardha'
 'Yavatmal' 'Chandrapur' 'Rajnandgaon' 'Angul' 'Cuttack' 'Khordha'
 'Bhadrak' 'Jagatsinghpur' 'Palghar' 'Mumbai Suburban' 'Ahmednagar'
 'Jalna' 'Aurangabad' 'Parbhani' 'Nanded' 'Bastar' 'Kalahandi' 'Ganjam'
 'Puri' 'Mumbai City' 'Raigad' 'Pune' 'Solapur' 'Latur' 'Nizamabad'
 'Medak' 'Peddapalli' 'Hanumakonda' 'Koraput' 'Srikakulam' 'Ratnagiri'
 'Satara' 'Kalaburagi' 'Bidar' 'Hyderabad' 'Nalgonda'
 'Bhadradri Kothagudem' 'Khammam' 'Kakinada' 'Visakhapatnam' 'Kolhapur'
 'Sangli' 'Bagalkote' 'Bijapur' 'Mahabubnagar' 'Raichur' 'Guntur'
 'Krishna' 'NTR' 'West Godavari' 'North Goa' 'Sindhudurg' 'South Goa'
 'Belagavi' 'Dharwad' 'Gadag' 'Ballari' 'Cuddalore' 'Nandyal' 'Kurnool'
 'Bapatla' 'Prakasam' 'Uttara Kannada' 'Haveri' 'Koppal' 'Davangere'
 'Chitradurga' 'Sri Sathya Sai' 'YSR' 'Nellore' 'Shivamogga'
 'Chikkamagaluru' 'Hassan' 'Lakshadweep' 'Tirupati' 'Chikkaballapura'
 'Tiruvallur' 'Chennai' 'Dakshina Kannada' 'Kodagu' 'Mandya' 'Mysuru'
 'Bengaluru Urban' 'Dharmapuri' 'Tirupattur' 'Vellore'
 'North & Middle Andaman' 'Kozhikode' 'Kannur' 'Malappuram' 'Nilgiris'
 'Coimbatore' 'Chamarajanagar' 'Salem' 'Thanjavur' 'Puducherry'
 'South Andaman' 'Palakkad' 'Ernakulam' 'Dindigul' 'Karur'
 'Tiruchirappalli' 'Karaikal' 'Nagapattinam' 'Alappuzha' 'Kollam'
 'Kottayam' 'Theni' 'Thrissur' 'Virudhunagar' 'Madurai' 'Ramanathapuram'
 'Nicobar' 'Thiruvananthapuram' 'Tirunelveli' 'Kanyakumari' 'Thoothukudi'
 'Jiribam' 'Bengaluru Rural' 'East Godavari']

Missing values in Delhi-period weather data:

date_of_record      0
month               0
season              0
station_name        0
state               0
district            0
avg_temp            0
min_temp           21
max_temp          118
wind_speed        256
air_pressure      327
elevation           0
latitude            0
longitude           0
rainfall           48
dtype: int64

Shape:
(7430, 15)

In [20]:
# Backup before cleaning
df_weather_raw = df.copy()

print("Backup created.")
print("Shape:", df.shape)

Backup created.
Shape: (970339, 15)

In [21]:
weather_numeric_cols = [
    "avg_temp",
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "elevation",
    "latitude",
    "longitude",
    "rainfall"
]

for col in weather_numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[weather_numeric_cols].dtypes)

avg_temp        float64
min_temp        float64
max_temp        float64
wind_speed      float64
air_pressure    float64
elevation         int64
latitude        float64
longitude       float64
rainfall        float64
dtype: object

In [22]:
fill_cols = [
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "rainfall"
]

for col in fill_cols:
    df[col] = df.groupby("station_name")[col].transform(
        lambda x: x.fillna(x.median())
    )

print("Station-wise median filling completed.")

Station-wise median filling completed.

In [23]:
missing_after = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

print(missing_after)

                Missing_Count  Missing_Percentage
date_of_record              0                 0.0
month                       0                 0.0
season                      0                 0.0
station_name                0                 0.0
state                       0                 0.0
district                    0                 0.0
avg_temp                    0                 0.0
min_temp                    0                 0.0
max_temp                    0                 0.0
wind_speed                  0                 0.0
air_pressure                0                 0.0
elevation                   0                 0.0
latitude                    0                 0.0
longitude                   0                 0.0
rainfall                    0                 0.0

In [24]:
# Check for completely duplicated rows
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [25]:
# Check duplicate station-date combinations
station_date_duplicates = df.duplicated(
    subset=["station_name", "date_of_record"]
).sum()

print("Duplicate station + date rows:", station_date_duplicates)

Duplicate station + date rows: 21703

In [26]:
# Remove duplicate station + date records
df = df.drop_duplicates(
    subset=["station_name", "date_of_record"],
    keep="first"
).reset_index(drop=True)

print("Shape after removing duplicates:", df.shape)

print(
    "Duplicate station + date rows after cleaning:",
    df.duplicated(
        subset=["station_name", "date_of_record"]
    ).sum()
)

Shape after removing duplicates: (948636, 15)
Duplicate station + date rows after cleaning: 0

In [27]:
# Check date range after duplicate removal
print("Date range:")
print(df["date_of_record"].min(), "→", df["date_of_record"].max())

# Check invalid/future dates
print("\nMissing dates:", df["date_of_record"].isna().sum())
print("Invalid dates:", (~pd.to_datetime(df["date_of_record"], errors="coerce").notna()).sum())

# Check duplicate station + date again
print(
    "\nDuplicate station + date rows:",
    df.duplicated(subset=["station_name", "date_of_record"]).sum()
)

Date range:
2015-01-01 00:00:00 → 2025-02-10 00:00:00

Missing dates: 0
Invalid dates: 0

Duplicate station + date rows: 0

In [28]:
# Check numerical columns for invalid negative values

numeric_checks = {
    "min_temp": (df["min_temp"] < -100).sum(),
    "max_temp": (df["max_temp"] < -100).sum(),
    "wind_speed": (df["wind_speed"] < 0).sum(),
    "air_pressure": (df["air_pressure"] < 0).sum(),
    "rainfall": (df["rainfall"] < 0).sum(),
    "elevation": (df["elevation"] < 0).sum()
}

print("Invalid / negative values:")
for col, count in numeric_checks.items():
    print(f"{col}: {count}")

Invalid / negative values:
min_temp: 0
max_temp: 0
wind_speed: 0
air_pressure: 0
rainfall: 0
elevation: 0

In [29]:
# Weather dataset: check categorical columns and station consistency

categorical_cols = [
    "month",
    "season",
    "station_name",
    "state",
    "district"
]

for col in categorical_cols:
    print(f"\n{col}")
    print("Unique values:", df[col].nunique())
    print(df[col].value_counts().head(10))

month
Unique values: 12
month
January      90886
December     80728
October      80299
July         79885
August       79213
March        78510
May          78274
November     77745
September    76459
June         76346
Name: count, dtype: int64

season
Unique values: 4
season
Winter          325894
Monsoon         235557
Summer          229141
Post-monsoon    158044
Name: count, dtype: int64

station_name
Unique values: 406
station_name
Srinagar                         3694
Thiruvananthapuram               3694
Gauhati                          3694
Hyderabad Airport                3694
Madras / Minambakkam             3694
Madras                           3694
Dibrugarh / Mohanbari            3694
Mangalore / Bajpe                3694
Bangalore / Hindustan Airport    3694
Bangalore                        3694
Name: count, dtype: int64

state
Unique values: 32
state
MH    95132
MP    86379
AP    81129
KA    75376
TN    72709
UP    71635
GJ    61988
RJ    56227
WB    42590
OR    41684
Name: count, dtype: int64

district
Unique values: 314
district
Visakhapatnam      13400
Udaipur            11004
Uttara Kannada     10614
Kachchh            10014
Raipur              9495
Lakshadweep         9345
Mumbai Suburban     8877
South Andaman       8875
Pune                8873
Coimbatore          8868
Name: count, dtype: int64

In [30]:
# Check numerical feature distributions and basic statistics

numeric_cols = [
    "avg_temp",
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "elevation",
    "latitude",
    "longitude",
    "rainfall"
]

print("Numerical feature summary:")
display(df[numeric_cols].describe().T)

Numerical feature summary:

,count,mean,std,min,25%,50%,75%,max
avg_temp,948636.0,25.677886,5.390662,-10.4000,23.1000,26.7000,29.1000,43.4000
min_temp,948636.0,20.713015,5.853834,-18.5000,17.4000,22.3000,25.0000,36.6000
max_temp,948636.0,31.240070,5.166909,-5.6000,29.0000,31.6000,34.0000,87.0000
wind_speed,948636.0,9.242546,4.521441,0.0000,6.2000,8.2000,11.3000,66.6000
air_pressure,948636.0,1009.388775,4.420700,922.6000,1007.6000,1009.3000,1012.0000,1036.5000
elevation,948636.0,295.946469,410.385137,0.0000,16.0000,135.0000,444.0000,2652.0000
latitude,948636.0,20.816324,6.235189,7.9833,15.8500,21.6500,25.4667,34.0833
longitude,948636.0,79.421966,5.863408,68.8500,75.3333,78.0833,82.7167,95.3833
rainfall,948636.0,3.968733,12.609797,0.0000,0.0000,0.0000,2.0000,485.9000

In [31]:
# Check for potential outliers using the IQR method

numeric_cols = [
    "avg_temp",
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "elevation",
    "rainfall"
]

outlier_summary = []

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = ((df[col] < lower) | (df[col] > upper)).sum()

    outlier_summary.append({
        "Column": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower_Bound": lower,
        "Upper_Bound": upper,
        "Outlier_Count": count,
        "Outlier_Percentage": round((count / len(df)) * 100, 2)
    })

outlier_df = pd.DataFrame(outlier_summary)

display(outlier_df)

,Column,Q1,Q3,IQR,Lower_Bound,Upper_Bound,Outlier_Count,Outlier_Percentage
0,avg_temp,23.1,29.1,6.0,14.10,38.10,38883,4.10
1,min_temp,17.4,25.0,7.6,6.00,36.40,18045,1.90
2,max_temp,29.0,34.0,5.0,21.50,41.50,63925,6.74
3,wind_speed,6.2,11.3,5.1,-1.45,18.95,39055,4.12
4,air_pressure,1007.6,1012.0,4.4,1001.00,1018.60,60408,6.37
5,elevation,16.0,444.0,428.0,-626.00,1086.00,42392,4.47
6,rainfall,0.0,2.0,2.0,-3.00,5.00,157532,16.61